### ISSUE TITLE
npm ci fails on latest image

### ISSUE THREAD

**Issue by AlbertoLopSie** [byCedric/expo-cli-images#3]
### Description of the bug
npm ci fails on latest image (May 15th)

### To Reproduce
run "npm ci" on a fresh image run into Gitlab CI/CD

#### Expected behavior
Should run fine as did until a few weeks ago

#### Actual behavior
It fails with the message in the attached screen

### Additional context
It work fine last tine I ran it on April 27th

<img width="1018" alt="Screen Shot 2020-05-16 at 12 26 03" src="https://user-images.githubusercontent.com/2622480/82123689-105f4880-9771-11ea-8f9b-a99beaa25fd7.png">

**Comment by byCedric** [comment]
Hi @AlbertoLopSie, sorry for the delay. This looks like something is up with the NPM cache. It partially downloads a dependency, `are-we-there-yet`. I don't think anything is wrong with the image itself, because it doesn't contain any cache (not NPM or Yarn). If you are still having issues with this, let me know!
